version: "3"
services:
  go:
    build:
      context: ./server/go
    container_name: login-go
    ports:
      - 5000:5000
    tty: true
    volumes:
      - ./server/go:/app
  mysql:
    image: mysql:8
    container_name: login-mysql
    ports:
      - 3306:3306
    volumes:
      - ./server/db/mysql_init:/docker-entrypoint-initdb.d
      - ./server/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: logintest
      MYSQL_PASSWORD: logintest
  react:
    image: node:15
    container_name: login-react
    ports:
      - 3000:3000
    volumes:
      - ./client/react:/app
    working_dir: /app
    command: yarn start
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: login-nginx
    ports:
      - 80:80
    tty: true
